name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create cookies file
      env:
        COOKIES: ${{ secrets.COOKIES }}
      run: echo "$COOKIES" > cookies.txt

    - name: Run bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: python bot.py
